### PR TITLE
Expose fewer condition types by leveraging status and reason.

### LINKED ISSUE #495: Resource claims can have failed and ready conditioned status simultaneously
We've observed that resource claims can have the `Failed` and `Ready` conditioned statuses simultaneously. For example:
 
```
    - LastTransitionTime: "2019-05-20T22:26:59Z"
      Message: ""
      Reason: ""
      Status: "True"
      Type: Ready
    - LastTransitionTime: "2019-05-20T22:29:00Z"
      Message: 'cannot update instance crossplane-system/redis-e4a01610-7b4d-11e9-9bb0-42010a8a0094:
        Operation cannot be fulfilled on cloudmemorystoreinstances.cache.gcp.crossplane.io
        "redis-e4a01610-7b4d-11e9-9bb0-42010a8a0094": the object has been modified;
        please apply your changes to the latest version and try again'
      Reason: Failed to set resource binding status
      Status: "True"
      Type: Failed
```

I believe this is because we don't unset conditions when we set failed in https://github.com/crossplaneio/crossplane/blob/3ee2da/pkg/controller/core/resource_controller.go#L257

### PR DESCRIPTION
**Pull request by negz**
**Description of your changes**
This slightly more opinionated implementation aims to 

* Prevent unintuitive statuses, for example a resource being "ready" and "failed" simultaneously.
* Provide some guard rails, such as removing `IsReady()` and friends, which encourage making decisions based on previously recorded rather than currently observed status.
* Align the way our conditioned statuses work a little more closely to the patterns used by Kubernetes proper (e.g. [on `Node`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#nodecondition-v1-core)).

To recap, today we have the following:
```go
const (
	// Pending means that the resource create request has been received and is waiting
        // to be fulfilled.
	Pending ConditionType = "Pending"

	// Creating means that the resource create request has been accepted and the
        // resource is in the process of being created.
	Creating ConditionType = "Creating"

	// Deleting means that the resource is in the process of being deleted.
	Deleting ConditionType = "Deleting"

	// Failed means that the resource is in a failure state, for example it failed to
        // be created.
	Failed ConditionType = "Failed"

	// Ready means that the resource creation has been successful and the resource
        // is ready to accept requests and perform operations.
	Ready ConditionType = "Ready"
)

// Condition contains details for the current condition of this pod.
type Condition struct {
	Type               ConditionType
	Status             corev1.ConditionStatus
	LastTransitionTime metav1.Time
	Reason             string
	Message            string
}

type ConditionStatus string

// These are valid condition statuses. "ConditionTrue" means a resource is in the condition.
// "ConditionFalse" means a resource is not in the condition. "ConditionUnknown" means kubernetes
// can't decide if a resource is in the condition or not. In the future, we could add other
// intermediate conditions, e.g. ConditionDegraded.
const (
	ConditionTrue    ConditionStatus = "True"
	ConditionFalse   ConditionStatus = "False"
	ConditionUnknown ConditionStatus = "Unknown"
)
```

Note that each contemporary condition has two states, and some context (i.e. `Reason` and `Message`) that largely go unused.

In the approach put forth by this PR there are only two conditions; `Ready` and `Synced`. The former represents the lifecycle of the managed resource while the latter represents the status of operations upon the resource. The condition status and reason are used to provide more information as to why the managed resource is or is not synced and ready.

**Which issue is resolved by this Pull Request:**
Resolves #495

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make generate`) has been run to update object specifications, if necessary.
- [ ] CRD manifests generation (`make manifests`) has been run to update CRD manifests yaml file specifications, if necessary.
- [ ] Update dependencies (`make vendor`) has been run to update `Gopkg.lock` file, if necessary
- [ ] RBAC permissions in `clusterrole.yaml` have been updated to include new types, if necessary
- [ ] All related commits have been squashed to improve readability.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by negz** [comment]
I expect this PR to break many test in its current state. I've refactored `ConditionedStatus` and updated one controller to use the new patterns in order to illustrate my intent. I'd like to get feedback before I undertake the task of refactoring the many places in which we currently use `ConditionedStatus`.

File: pkg/apis/core/v1alpha1/condition.go [hunk 1]
```diff
@@ -17,181 +17,229 @@ limitations under the License.
...
+// A ConditionReason represents the reason a resource is in a condition.
+type ConditionReason string
+
+// Condition reasons.
+const (
+	// Available indicates the managed resource is available for use.
+	Available ConditionReason = "Managed resource is available"
+
+	// Unavailable indicates the managed resource is not available for use.
+	Unavailable ConditionReason = "Managed resource is unavailable"
```
Comment (ichekrygin) [inline pkg/apis/core/v1alpha1/condition.go]: What is the difference between `Unavailable.Status = true` and `Available.Status = false`?

File: pkg/apis/core/v1alpha1/condition.go [hunk 2]
```diff
@@ -17,181 +17,229 @@ limitations under the License.
...
+	// Synced managed resources are believed to be in sync with the Kubernetes
+	// resources that manage their lifecycle.
+	Synced ConditionType = "Synced"
+)
+
+// A ConditionReason represents the reason a resource is in a condition.
+type ConditionReason string
+
+// Condition reasons.
+const (
```
Comment (ichekrygin) [inline pkg/apis/core/v1alpha1/condition.go]: General thought.

I was never :100: sure if using "shared" conditions was the right approach. 
While I agree that many (if not all) resources share the same base condition, at the same time I do think that resource conditions should reflect specific resource state, i.e. to be resource specific.

The way @negz formulated `const` conditions value make them better suitable for multiple resources. Whereas in the past we had, for example, a `Running` condition, which did not make sense for "not-runnable" resources like storage buckets. So I think this is an improvement. 

With that said, do we think this is the right direction, i.e. golbal conditions vs. resource specific ones?
Again, this is just a thought and not a challenge, since I do see some cases of reusability, but not :100: sure.

What do you think?

File: pkg/apis/core/v1alpha1/condition.go (hunk 1 above)
Comment (negz) [reply pkg/apis/core/v1alpha1/condition.go]: It's not as obvious as it should be, but`ConditionStatus` corresponds to `ConditionType`, not `ConditionReason`. The hierarchy is something like:

1. `ConditionType` - What type of condition is this?
2. `ConditionStatus` - Is the condition true, false, or unknown?
3. `ConditionReason` - Why is the condition true, false or unknown?

So in this PR the subset of combinations we use are:

* `Type=Ready`
  * `Status=True`
    * `Reason=Available`
  * `Status=False`
    * `Reason=Unavailable` - Resource is unready because it's unavailable.
    * `Reason=Creating` - Resource is unready because it's 
    * `Reason=Deleting`
* `Type=Synced`
  * `Status=True`
    * There's actually no corresponding `Reason` here. Perhaps there should be something like `ReconcileSuccess`.
  * `Status=False`
    * `Reason=Error`- Resource was not synced because we encountered an error.

Does that make sense?

File: pkg/apis/core/v1alpha1/condition.go (hunk 2 above)
Comment (negz) [reply pkg/apis/core/v1alpha1/condition.go]: Yeah I also wondered this. My suspicion is that these reasons will be appropriate for at least 80% of cases, especially our main functionality of managing cloud resources. I'm not sure they make as much sense in the edge cases like controllers that manage Workloads. I think I'll have a stronger opinion on this once I've attempted to adapt all of our existing controllers to use these conditions.

Given I suspect these reasons will be suitable for 80% of our controllers, perhaps we could consider an approach in which we default to using these shared conditions, but fall back to defining our own for controllers where they don't make sense?

File: pkg/apis/core/v1alpha1/condition.go (hunk 1 above)
Comment (negz) [reply pkg/apis/core/v1alpha1/condition.go]: I just pushed a commit that tries to make this a little more obvious by adding docstrings to the fields of the `Condition` struct.

File: pkg/apis/core/v1alpha1/condition.go [hunk 3]
```diff
@@ -17,181 +17,229 @@ limitations under the License.
...
+	// Available indicates the managed resource is available for use.
+	Available ConditionReason = "Managed resource is available"
```
[the remark this answers is not in the document]
Comment (negz) [reply pkg/apis/core/v1alpha1/condition.go]: Do you mean the difference between `Available` and `Ready`? I don't think we've had a `Running` condition.

Think of any `Reason` as "the reason this resource  is in its current state". For example "The `Reason` this resource's `Ready` condition is status `True` because the managed resource is `Available`". In this specific example the `Reason` is redundant - the _only_ reason a resource can be ready is because it's available.

This pattern starts to make a little more sense when there's multiple reasons a condition can be in a particular status. For example "the `Reason` this resource's `Ready` condition is status `False` is because the managed resource is `Deleting`. The resource being `Unavailable`, or `Creating` are also reasons the `Ready` condition may be `False`.

Note that none of this is really of my design - I'm copying the patterns from Kubernetes Node and Pod conditions, which I presume is what Crossplane modeled its `ConditionedStatus` on.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#nodecondition-v1-core
https://kubernetes.io/docs/concepts/architecture/nodes/#condition 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podcondition-v1-core

**Comment by negz** [comment]
@ichekrygin @jbw976 @displague Please take another look.

My initial plan with this PR was to refactor the entire codebase in one fell swoop, but I think doing so would have been highly prone to merge conflicts over time, and nigh on impossible to review. Instead I decided to rename `ConditionedStatus` to `DeprecatedConditionedStatus`, then introduce the newer implementation of `ConditionedStatus` in a separate commit. My hope is this will allow us to refactor the codebase over time and avoid one monster PR.

File: pkg/apis/core/v1alpha1/condition.go (hunk 1 above)
Comment (negz) [reply pkg/apis/core/v1alpha1/condition.go]: I'm going to mark this resolved - feel free to reopen if you have more thoughts!
