### PR TITLE
fixing issue #681

### LINKED ISSUE #681: EKS worker-node `ami`s need to be tied to the provisioned Kubernetes cluster version
### What happened?
When creating an EKS cluster, the [`Cluster Version`] is optional. If not provided [the latest version in Amazon EKS is used]. In the other hand, the worker node `ami` images are [tied to specific cluster versions]. However the `ami` image IDs that are currently [hard coded] are not tied to cluster versions. This creates two problems:
1. The right `ami` image for a given cluster version cannot be determined
1. Even if the above problem is fixed, whenever the default version in EKS (the latest) is updated, creating an EKS cluster without specifying the [`Cluster Version`] fails because the appropriate `ami` won't be known.

### How can we reproduce it?

Applying the current [WordPress workload on AWS]

### What environment did it happen in?
Crossplane version: master@6cac2c279038619242d85665e99a0ab0260960f2
Is this a regression: No

[`Cluster Version`]: https://github.com/crossplaneio/crossplane/blob/master/aws/apis/compute/v1alpha1/types.go#L114
[the latest version in Amazon EKS is used]: https://github.com/aws/aws-sdk-go-v2/blob/v2.0.0-preview.5/service/eks/api.go#L442-L444
[tied to specific cluster versions]: https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html
[hard coded]: https://github.com/crossplaneio/crossplane/blob/master/aws/apis/compute/v1alpha1/types.go#L57-L62
[WordPress workload on AWS]: https://github.com/crossplaneio/crossplane/blob/master/docs/workloads/aws/wordpress-aws.md

### PR DESCRIPTION
**Pull request by soorena776**
### Description of your changes

This pr fixes #681 as following:
1. Track the created cluster's version in its `State`, to use for retrieving the corresponding AMI
1. Use ec2 client's `DescribeImages` method (available in aws sdk 1.16) to retrieve AMIs that are specific for created cluster's region and version
1. Remove the hardcoded AMIs
1. Add 80+% test coverage for the new code 
1. Make the existing unittests work

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [ ] Updated the RBAC permissions in [`clusterrole.yaml`] to include any new types.

[documentation]: https://github.com/crossplaneio/crossplane/tree/master/docs
[examples]: https://github.com/crossplaneio/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplaneio/crossplane/tree/master/PendingReleaseNotes.md
[`clusterrole.yaml`]: https://github.com/crossplaneio/crossplane/blob/master/cluster/charts/crossplane/templates/clusterrole.yaml

### CODE REVIEW

File: pkg/clients/aws/eks/eks.go [hunk 1]
```diff
@@ -86,21 +95,49 @@ type Client interface {
...
 	sts            *sts.STS
 	cloudformation cfc.Client
 }
 
 // NewClient return new instance of the crossplane client for a specific AWS configuration
 func NewClient(config *aws.Config) Client {
-	return &eksClient{eks.New(*config), sts.New(*config), cfc.NewClient(config)}
+
+	// the current functionality in ec2 instance (describe images) only
+	// is available in aws sdk v1.23. Since instantiating an ec2 client
```
Comment (soorena776) [inline pkg/clients/aws/eks/eks.go]: v1.16+

File: aws/apis/compute/v1alpha1/types.go [hunk 2]
```diff
@@ -220,6 +209,8 @@ type EKSClusterStatus struct {
 	State string `json:"state,omitempty"`
 	// ClusterName identifier
 	ClusterName string `json:"resourceName,omitempty"`
```
Comment (hasheddan) [inline aws/apis/compute/v1alpha1/types.go]: Do we want the JSON fields to match the struct fields here?

**Comment by jbw976** [comment]
I have no idea why it says I closed it when i just submitted the comment now, sorry about that!!

File: pkg/clients/aws/eks/eks.go [hunk 3]
```diff
@@ -86,21 +95,57 @@ type Client interface {
...
-	return &eksClient{eks.New(*config), sts.New(*config), cfc.NewClient(config)}
+	return &eksClient{eks.New(*config), ec2.New(buildAWSSession((config))), sts.New(*config), cfc.NewClient(config)}
+}
+
+func buildAWSSession(config *aws.Config) *session.Session {
+	// the current functionality in ec2 instance (describe images) only
+	// is available in aws sdk v1.16+. Since instantiating an ec2 client
+	// uses a session instance, the following uses the existing aws config,
+	// and creates the session for sdk 1.16+
+	// TODO (javad): Remove this once we upgrade aws sdk to 1.16+
```
[the remark this answers is not in the document]
Comment (soorena776) [reply pkg/clients/aws/eks/eks.go]: looks like it's available in a different format. I'll use that one
https://github.com/aws/aws-sdk-go-v2/blob/master/service/ec2/api_op_DescribeImages.go#L187

File: aws/apis/compute/v1alpha1/types.go (hunk 2 above)
Comment (soorena776) [reply aws/apis/compute/v1alpha1/types.go]: That's a good question, but seems like that hasn't been the case (see `ClusterName string` one line above)

File: pkg/clients/aws/eks/eks.go [hunk 4]
```diff
@@ -228,6 +270,80 @@ func (e *eksClient) ConnectionToken(name string) (string, error) {
...
+		})
+
+	return out.Images, err
+}
+
+func getMostRecentImage(images []*ec2.Image) *ec2.Image {
+	var result *ec2.Image
+	for _, img := range images {
+		if result == nil || aws.StringValue(result.CreationDate) < aws.StringValue(img.CreationDate) {
+			result = img
```
Comment (jbw976) [inline pkg/clients/aws/eks/eks.go]: is this an instance of the infamous golang range gotcha? https://github.com/golang/go/wiki/Range#gotchas

i've been bitten by that numerous times and I may have overcorrected to being too paranoid about it now, but hopefully you were able to test and confirm this function correctly finds the most recent image, esp. when the most recent is NOT the last item in the list.

File: pkg/clients/aws/eks/eks_test.go [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+}
+
+func TestGetMostRecent(t *testing.T) {
+	g := gomega.NewGomegaWithT(t)
+
+	cases := []struct {
+		expected string
+	}{
+		// img1 is the most recent image
+		{"img1"},
```
Comment (jbw976) [inline pkg/clients/aws/eks/eks_test.go]: consider testing getMostRecent with more than 1 image in the list

Comment (soorena776) [reply pkg/clients/aws/eks/eks_test.go]: the `"img1"` is not the set, it's the expected value. This is testing against `mockImages` list which has 3 items

File: pkg/clients/aws/eks/eks.go [hunk 6]
```diff
@@ -86,21 +95,57 @@ type Client interface {
...
+
+func buildAWSSession(config *aws.Config) *session.Session {
+	// the current functionality in ec2 instance (describe images) only
+	// is available in aws sdk v1.16+. Since instantiating an ec2 client
+	// uses a session instance, the following uses the existing aws config,
+	// and creates the session for sdk 1.16+
+	// TODO (javad): Remove this once we upgrade aws sdk to 1.16+
+	creds, err := config.Credentials.Retrieve()
+	if err != nil {
+		panic(err)
```
[the remark this answers is not in the document]
Comment (soorena776) [reply pkg/clients/aws/eks/eks.go]: The behavior that I was hoping to implement here was a `MustSucceed`. This however is removed since I switched back to sdk-v2

File: pkg/clients/aws/eks/eks.go [hunk 7]
```diff
@@ -86,21 +95,57 @@ type Client interface {
...
+	}
+	if err := os.Setenv("AWS_ACCESS_KEY_ID", creds.AccessKeyID); err != nil {
```
[the remark this answers is not in the document]
Comment (soorena776) [reply pkg/clients/aws/eks/eks.go]: removed, as used sdk-v2

File: pkg/clients/aws/eks/eks.go (hunk 4 above)
Comment (soorena776) [reply pkg/clients/aws/eks/eks.go]: good point. using a regular for loop instead

File: pkg/clients/aws/eks/eks_test.go (hunk 5 above)
Comment (soorena776) [reply pkg/clients/aws/eks/eks_test.go]: the used list here (`mockImages`) has 3 instances

File: pkg/clients/aws/eks/eks.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (soorena776) [reply pkg/clients/aws/eks/eks.go]: I used sdk-v2. The reasons:
1. avoiding the hack to get the credentials from sdk 2.0 `config` to build a new session for sdk 1.16
2. compatibility with exiting aws go sdk
3. compatibility with existing mocking technique

**Comment by soorena776** [comment]
@jbw976 I switched back using aws-go-sdk-v2. I kept the older commit for future comparison purposes in the future, if we decided to migrate.

File: aws/apis/compute/v1alpha1/types.go (hunk 2 above)
Comment (displague) [reply aws/apis/compute/v1alpha1/types.go]: I think we'll offer a better experience matching the upstream fields precisely (within the conventions of Go variable naming).  No guessing required for those that know the AWS API, tools, or terminology.

We could take advantage of the field documentation to more elaborately explain that the resource name is the name of the EKS Cluster.  Likewise for `ClusterVersion`.  Are these the only fields that do not conform to their remote names?

There are no embedding conflicts with `ResourceName` and `ResourceVersion` https://github.com/crossplaneio/crossplane/blob/master/apis/core/v1alpha1/resource.go#L143-L146
